config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#index'

  resource :game, :only => [:new, :show, :update, :destroy]
  
end

app/models/game.rb
class Game
  include ActiveModel::AttributeMethods, ActiveModel::Serializers::JSON

  class GameOverError < StandardError; end

  # Define a limit of failed attempts
  MAX_FAILED_ATTEMPTS = 5
  attr_accessor :word
  attr_accessor :selected_letters



  def initialize
    @words = %w"learning ruby education rails computer mobile javascript sinatra github html css light earth machine book
    news yahoo google internet awesome slack america rogue angular jquery stack software"
    @word = @words[rand(@words.length) - 1].upcase
    @selected_letters = []
  end

  # Declare an attributes hash which contains the attributes I want to serialize
  def attributes
    {'word' => nil,
     'selected_letters' => nil}
  end

  def attributes=(hash)
    hash.each do |key, value|
      send("#{key}=", value)
    end
  end


  # Accepts a letter, and returns true or false
  # Based on whether the word contains the letter
  # Count how many of the letters are included
  def failed_attempts
    selected_letters.select { |letter| !word.include?(letter) }.size
  end

  # Convert word into an array of it's characters 
  # Then subtract the selected letters from array
  def guessed?
    (word.split('') - selected_letters).empty?
  end

  def finished?
    failed_attempts >= MAX_FAILED_ATTEMPTS || guessed?
  end

  def select!(letter)
    raise GameOverError if finished?
    selected_letters << letter unless selected_letters.include? letter
    word.include? letter
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_game

  # Loads and keeps the current game
  def current_game
    @current_game ||= load_current_game
  end

  # Sets both the @current_game variable & the session's 
  # serialized current game with the given game
  def set_current_game(game)
    @current_game = game
    session[:serialized_current_game] = game.present? ? game.to_json : nil
  end

  # Serialize the current game to session
  def update_current_game
    set_current_game @current_game
  end

  protected

  def load_current_game
    Game.new.from_json(session[:serialized_current_game]) if session[:serialized_current_game].present?
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    set_current_game Game.new
    redirect_to game_path
  end

  def show
  end

  def update
    current_game.select! params[:letter]
    update_current_game
  rescue Game::GameOverError
    flash[:alert] = 'This game is finished...'
  ensure
    redirect_to game_path
  end

  def destroy
    set_current_game nil
    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/games/destroy.html.erb
<h1>Games#destroy</h1>
<p>Find me in app/views/games/destroy.html.erb</p>

app/views/games/show.html.erb
<div class="row">
    <!-- <div class="small-12 medium-4 columns"> -->
        <div id="gallows" class="gallows gallows-state-<%= current_game.failed_attempts %>">

        </div>
    </div>

    <div class="row">
        <h1 class="word column align-self-top">
            <% current_game.word.split('').each do |letter| %>
                        
                <%= current_game.finished? || current_game.selected_letters.include?(letter) ? letter : '_' %>
                      
            <% end %>
        </h1>
    </div>

        <% if current_game.finished? %>
            <div class="row game-status">
                <div class="small-12 columns text-center">
                    <% if current_game.guessed? %>
                        <div id="notice_wrapper">
                          <p class="alert">You Win!<br><%= link_to "Play again?", new_game_path %> </p></br>
                        </div>
                    <% else %>
                        <div id="notice_wrapper">
                          <p class="alert">Game Over<br><%= link_to "Try again?", new_game_path %> </p></br>
                        </div>
                    <% end %>
                </div>
            </div>
        <% end %>

        <%= form_for :game, :url => game_path, :method => :patch do |form| %>
            <div class="row medium-6 columns">
                <div class="letters">
                    <% ('A'..'Z').each do |letter| %>
            
                        <%
                            if current_game.selected_letters.include? letter
                                button_class = current_game.word.include?(letter) ? 'success' : 'alert'
                            end
                        %>
                        <div class="small-2 medium-2 columns text-center">
                            <div class="letter">
                                <%= form.submit letter, :name => 'letter', :class => "button expand #{button_class}" %>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        <% end %>

        <div class="row">
            <div class="game-actions">
                <!-- Decide if i want to take this line out -->
                <div class="small-2 <%= current_game.finished? ? '' : 'medium-7' %> columns text-center">
                    <%= link_to root_path(:method => :delete), :class => 'hollow button expand success' do %>
                        <i class="fa fa-home"></i> Go Back
                    <% end %>
                </div>

                <% unless current_game.finished? %>
                    <div class="small-2 medium-4 columns">
                        <%= link_to game_path, :class => 'hollow button expand alert', :method => :delete do %>
                            <i class="fa fa-fire"></i> End game
                        <% end %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/games/update.html.erb
<h1>Games#update</h1>
<p>Find me in app/views/games/update.html.erb</p>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hangman</title>
  </head>
  
  <body class="home">
    <div class="row">
        <div class="small-12 columns text-center">
            <h1 id="welcome">Welcome to Hangman!</h1>
        </div>
    </div>

    <div class="row">
        <div class="small-12 <%= current_game.present? && !current_game.finished? ? 'medium-6' : '' %> columns text-center">
            <%= link_to new_game_path, :class => 'button expand' do %>
                <i class="fa fa-play"> New game</i>
            <% end %>
        </div>

        <% if current_game.present? && !current_game.finished? %>
            <div class="small-12 medium-6 columns text-center">
                <%= link_to game_path, :class => 'button expand' do %>
                    <i class="fa fa-refresh"> Continue game</i>
                <% end %>
            </div>
        <% end %>
   
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
<!--     <script>
        $(document).ready(function() {
            setTimeout(function() {
                $('#notice_wrapper').fadeOut("slow", function() {
                    $(this).remove();
                });
            }, 4500);
        });
    </script> -->

  </body>
</html>